<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Étape 2 — Demande de Crédit. One credit request per application (1:1). `n_demande`
        // is never customer-entered — it's generated by ApplicationNumberService and written
        // by the backend only (see UpdateCreditRequestRequest / CreditRequestController).
        Schema::create('credit_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('credit_application_id')->unique()->constrained()->cascadeOnDelete();
            $table->string('n_demande')->unique()->nullable();
            $table->string('identifiant_personne')->nullable();
            $table->string('nom_ou_rs')->nullable();
            $table->string('prenom_ou_dc')->nullable();
            $table->string('type_pid')->nullable();
            $table->string('numero_pid')->nullable();
            $table->string('origine')->nullable();
            $table->date('date_depot')->nullable();
            $table->date('date_reception')->nullable();
            $table->string('type_demande')->nullable();
            $table->string('code_devise')->nullable();
            $table->decimal('montant_global_sollicite', 14, 3)->nullable();
            $table->unsignedSmallInteger('nombre_credits_sollicites')->nullable();
            $table->string('unite_depot')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('credit_requests');
    }
};
