<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('audit_logs', function (Blueprint $table) {
            $table->string('key_version', 40)->nullable()->after('integrity_hash');
        });
        Schema::table('audit_chain_heads', function (Blueprint $table) {
            $table->string('key_version', 40)->nullable()->after('last_audit_log_id');
        });

        // Rows generated by the previous implementation used APP_KEY and did not include
        // a version field in their canonical payload. Tagging preserves their exact hash format.
        DB::table('audit_logs')->whereNotNull('integrity_hash')->update(['key_version' => 'legacy-app-key']);
        DB::table('audit_chain_heads')->whereNotNull('last_hash')->update(['key_version' => 'legacy-app-key']);
    }

    public function down(): void
    {
        Schema::table('audit_chain_heads', fn (Blueprint $table) => $table->dropColumn('key_version'));
        Schema::table('audit_logs', fn (Blueprint $table) => $table->dropColumn('key_version'));
    }
};
