<?php

namespace Database\Seeders;

use App\Models\Branch;
use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    /**
     * The official real BTS (Banque Tunisienne de Solidarité) regional branches network across
     * Tunisia with exact real coordinates, addresses, phone numbers, and fax.
     */
    public function run(): void
    {
        $agencies = [
            [
                'name' => 'LA SUCCURSALE',
                'ville' => 'Tunis',
                'delegation' => 'Bab Bhar',
                'address' => '56, AV MED V 1002 TUNIS',
                'phone' => '70 018 467',
                'fax' => '70845537',
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.812982,
                'longitude' => 10.184276,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => true,
            ],
            [
                'name' => 'Agence BTS Bardo',
                'ville' => 'Tunis',
                'delegation' => 'Le Bardo',
                'address' => '2 Avenue Bayrem ettounsi Bardo',
                'phone' => '70 282 956 / 70 282 950',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.807046,
                'longitude' => 10.134539,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'CR ARIANA',
                'ville' => 'Ariana',
                'delegation' => 'Ettadhamen',
                'address' => '120 AV IBN KHALDOUNE, Ettadhamen - Ariana',
                'phone' => '70 282 955 / 70 282 803',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.838545,
                'longitude' => 10.112674,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'CR MANOUBA',
                'ville' => 'Manouba',
                'delegation' => 'Manouba',
                'address' => '113 AV HABIB BOURGUIBA, MANOUBA',
                'phone' => '70 282 825 / 70 282 883',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.814623,
                'longitude' => 10.099357,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'CR BEN AROUS',
                'ville' => 'Ben Arous',
                'delegation' => 'Mégrine',
                'address' => 'ROUTE GP1 KM7 IMM BOUCHIKH MEGRINE BEN AROUS',
                'phone' => '71 425 385',
                'fax' => '71 426 942',
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.756929,
                'longitude' => 10.244429,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS BIZERTE',
                'ville' => 'Bizerte',
                'delegation' => 'Bizerte Nord',
                'address' => '9 AV HABIB BOURGUIBA, BIZERTE',
                'phone' => '70 282 820 / 70 282 826',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 37.274838,
                'longitude' => 9.875792,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS BEJA',
                'ville' => 'Béja',
                'delegation' => 'Béja Nord',
                'address' => 'Rue OKBA IBN NAFAA, BEJA',
                'phone' => '70 282 810 / 70 282 805',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.726984,
                'longitude' => 9.184645,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS JENDOUBA',
                'ville' => 'Jendouba',
                'delegation' => 'Jendouba',
                'address' => '9 AV FARHAT HACHED, JENDOUBA',
                'phone' => '70 282 838 / 70 282 864',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.501349,
                'longitude' => 8.778774,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS SILIANA',
                'ville' => 'Siliana',
                'delegation' => 'Siliana',
                'address' => 'AV TAIEB MHIRI, SILIANA',
                'phone' => '70 282 923 / 70 282 927',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.084235,
                'longitude' => 9.374945,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS LE KEF',
                'ville' => 'Le Kef',
                'delegation' => 'Le Kef Ouest',
                'address' => 'Avenue Habib Bourguiba 7100, LE KEF',
                'phone' => '70 282 849 / 70 282 841',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.178475,
                'longitude' => 8.706697,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'CR NABEUL',
                'ville' => 'Nabeul',
                'delegation' => 'Nabeul',
                'address' => 'RUE MED BEN HMIDA KARMA, NABEUL',
                'phone' => '70 282 899 / 70 282 897',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.454854,
                'longitude' => 10.741255,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS KAIROUAN',
                'ville' => 'Kairouan',
                'delegation' => 'Kairouan Nord',
                'address' => 'Rue AL KADI NOOMANE, KAIROUAN',
                'phone' => '70 282 876 / 70 282 845',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 35.671971,
                'longitude' => 10.103838,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS KASSERINE',
                'ville' => 'Kasserine',
                'delegation' => 'Kasserine Nord',
                'address' => 'NOUVELLE CITE ADMINISTRATIVE., KASSERINE',
                'phone' => '70 282 850 / 70 282 854',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 35.166187,
                'longitude' => 8.831765,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS SIDI BOUZID',
                'ville' => 'Sidi Bouzid',
                'delegation' => 'Sidi Bouzid Ouest',
                'address' => 'AV HABIB BOURGUIBA, SIDI BOUZID',
                'phone' => '70 282 857 / 70 282 920',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 35.038210,
                'longitude' => 9.487402,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'CR ZAGHOUAN',
                'ville' => 'Zaghouan',
                'delegation' => 'Zaghouan',
                'address' => 'RUE AHMED MBAREK, ZAGHOUAN',
                'phone' => '70 282 806 / 70 282 949',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.407049,
                'longitude' => 10.141824,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS MAHDIA',
                'ville' => 'Mahdia',
                'delegation' => 'Mahdia',
                'address' => 'Avenue du 2 Mars 1934, MAHDIA',
                'phone' => '70 282 896 / 70 282 873',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 35.506376,
                'longitude' => 11.054818,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS MONASTIR',
                'ville' => 'Monastir',
                'delegation' => 'Monastir',
                'address' => 'IMMEUBLE LES JARDINS, ZONE DE STADE, Monastir 5000',
                'phone' => '70 282 871 / 70 282 893',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 35.776602,
                'longitude' => 10.816571,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS SFAX',
                'ville' => 'Sfax',
                'delegation' => 'Sfax Ville',
                'address' => 'AVENUE MAJIDA BOULILA, IMM.DIAR EL WAFA, SFAX',
                'phone' => '70 282 914 / 70 282 910',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 34.737619,
                'longitude' => 10.750959,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS GAFSA',
                'ville' => 'Gafsa',
                'delegation' => 'Gafsa Sud',
                'address' => 'AV DE L\'EVACUATION (AL JALAA), GAFSA',
                'phone' => '70 282 833 / 70 282 832',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 34.418505,
                'longitude' => 8.785479,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS TOZEUR',
                'ville' => 'Tozeur',
                'delegation' => 'Tozeur',
                'address' => '134, AV FARHAT HACHED TOZEUR',
                'phone' => '70 282 944 / 70 282 945',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 33.918773,
                'longitude' => 8.134711,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS KEBILI',
                'ville' => 'Kébili',
                'delegation' => 'Kébili Sud',
                'address' => 'AV NALOUTE KEBILI',
                'phone' => '70 282 859 / 70 282 858',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 33.704974,
                'longitude' => 8.970863,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS GABES',
                'ville' => 'Gabès',
                'delegation' => 'Gabès Ville',
                'address' => '292 AV HABIB BOURGUIBA, JARA GABES',
                'phone' => '70 282 829 / 70 282 831',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 33.888773,
                'longitude' => 10.096886,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS MEDENINE',
                'ville' => 'Médenine',
                'delegation' => 'Médenine Nord',
                'address' => 'IMM. LE DEVELOPPEMENT, MEDENINE',
                'phone' => '70 282 886 / 70 282 885',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 33.345076,
                'longitude' => 10.490879,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence TATAOUINE',
                'ville' => 'Tataouine',
                'delegation' => 'Tataouine Nord',
                'address' => 'AV AHMED TLILI, TATAOUINE',
                'phone' => '70 282 939 / 70 282 942',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 32.930405,
                'longitude' => 10.448484,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence SFAX 2',
                'ville' => 'Sfax',
                'delegation' => 'Sakiet Ezzit',
                'address' => 'Route Tunis Km 6 , Avenue Monji Slim Sakiet Ezzit Sfax 3021',
                'phone' => '70 282 906 / 70 282 911',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 34.798999,
                'longitude' => 10.756657,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence ARIANA 2',
                'ville' => 'Ariana',
                'delegation' => 'Ariana Ville',
                'address' => 'Avenue Habib Bourguiba . Ariana',
                'phone' => '70 282 957 / 70 282 800',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.851216,
                'longitude' => 10.183745,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence BTS Lafayette',
                'ville' => 'Tunis',
                'delegation' => 'Bab Bhar',
                'address' => '11 Rue Ibn Jazar Lafayette Tunis',
                'phone' => '70 282 951 / 70 282 953',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 36.814134,
                'longitude' => 10.181431,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
            [
                'name' => 'Agence SOUSSE',
                'ville' => 'Sousse',
                'delegation' => 'Sousse Ville',
                'address' => 'AV JAOUHARET ESSAHEL KHZEMA CHARKIA SOUSSE',
                'phone' => '70 282 937 / 70 282 896',
                'fax' => null,
                'opening_hours' => '08:00 - 16:30 (Lun - Ven)',
                'latitude' => 35.850284,
                'longitude' => 10.607734,
                'daily_capacity' => 4,
                'slot_start_time' => '09:00:00',
                'slot_end_time' => '16:00:00',
                'is_default' => false,
            ],
        ];

        $names = [];
        $defaultBranch = null;

        foreach ($agencies as $agency) {
            $branch = Branch::updateOrCreate(
                ['name' => $agency['name']],
                $agency
            );
            $names[] = $agency['name'];
            if ($agency['is_default'] ?? false) {
                $defaultBranch = $branch;
            }
        }

        if ($defaultBranch) {
            $obsoleteBranches = Branch::whereNotIn('name', $names)->get();
            foreach ($obsoleteBranches as $old) {
                \App\Models\Appointment::where('branch_id', $old->id)->update(['branch_id' => $defaultBranch->id]);
                \App\Models\CreditApplication::where('branch_id', $old->id)->update(['branch_id' => $defaultBranch->id]);
                \App\Models\StaffUser::where('branch_id', $old->id)->update(['branch_id' => $defaultBranch->id]);
                $old->delete();
            }
        }
    }
}
