<?php

namespace App\Services\DocumentStorage;

use App\Models\CreditApplication;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use RuntimeException;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Shared, driver-independent behavior for the two DocumentStorage implementations:
 * content sniffing against the configured MIME allowlist, server-generated file names,
 * per-application path isolation, traversal defence and the download response headers.
 * The only thing a subclass contributes is which filesystem disk backs the operations.
 */
abstract class BaseDocumentStorage implements DocumentStorage
{
    abstract protected function disk(): string;

    protected const DISK_ROOT_NAME = 'documents';

    public function store(CreditApplication $application, UploadedFile $file): string
    {
        $maxBytes = (int) config('credit_documents.max_size_kb') * 1024;
        if ($file->getSize() > $maxBytes) {
            throw ValidationException::withMessages([
                'file' => 'The file is larger than the allowed '.config('credit_documents.max_size_kb').' KB.',
            ]);
        }

        $sniffed = $this->sniffMimeType($file);
        $extension = $this->extensionForMimeType($sniffed);

        if ($extension === null) {
            throw ValidationException::withMessages([
                'file' => 'The file type ('.$sniffed.') is not allowed.',
            ]);
        }

        $path = $this->isolatedPath($application, Str::uuid()->toString().'.'.$extension);

        Storage::disk($this->disk())->put($path, file_get_contents($file->getRealPath()));

        return $path;
    }

    public function exists(string $path): bool
    {
        $this->assertSafePath($path);

        return Storage::disk($this->disk())->exists($path);
    }

    public function delete(string $path): bool
    {
        $this->assertSafePath($path);

        return Storage::disk($this->disk())->delete($path);
    }

    public function response(string $path, string $downloadName, string $mimeType): BinaryFileResponse|StreamedResponse
    {
        $this->assertSafePath($path);

        if (! Storage::disk($this->disk())->exists($path)) {
            throw new RuntimeException('Document file not found on storage.');
        }

        return Storage::disk($this->disk())->response(
            $path,
            $this->sanitizeDownloadName($downloadName),
            [
                // Content-Disposition with the filename (plus RFC 5987 fallback for non-ASCII
                // names) is generated by the disk's response() from the disposition argument.
                'Content-Type' => $mimeType,
                'X-Content-Type-Options' => 'nosniff',
            ],
            'attachment',
        );
    }

    public function size(string $path): int
    {
        $this->assertSafePath($path);

        return Storage::disk($this->disk())->size($path);
    }

    /**
     * Every application's files live in their own folder — isolation-by-construction, so an
     * application id can never cross into another application's (or the disk root's) files.
     */
    protected function isolatedPath(CreditApplication $application, string $fileName): string
    {
        return 'application-'.$application->id.'/'.$fileName;
    }

    /**
     * Rejects paths containing traversal or absolute segments. disk_path is server-generated
     * (never client input), so this is defence-in-depth rather than the primary control.
     */
    protected function assertSafePath(string $path): void
    {
        if ($path === '' || str_contains($path, '..') || Str::startsWith($path, '/') || str_contains($path, '\\')) {
            throw new RuntimeException('Unsafe document path.');
        }
    }

    /** finfo content sniff — the authoritative MIME, independent of the client's declared extension. */
    protected function sniffMimeType(UploadedFile $file): string
    {
        $finfo = new \finfo(FILEINFO_MIME_TYPE);

        $mime = $finfo->file($file->getRealPath());

        return is_string($mime) ? strtolower($mime) : 'application/octet-stream';
    }

    /** The allowed extension whose sniffed-MIME allowlist contains $mime, or null if none. */
    protected function extensionForMimeType(string $mime): ?string
    {
        foreach (config('credit_documents.allowed_mime_types', []) as $extension => $mimes) {
            if (in_array($mime, $mimes, true)) {
                return $extension;
            }
        }

        return null;
    }

    /** ASCII-safe name for Content-Disposition, plus an RFC 5987 fallback for the original. */
    protected function sanitizeDownloadName(string $name): string
    {
        $name = preg_replace('/[\x00-\x1F\x7F"\\\\\/]+/u', '_', (string) $name) ?? '_';

        return $name;
    }
}
